from PyQt6 import QtCore, QtGui, QtWidgets

class Ui(object):
    def setupUi(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(709, 640, 151, 35))
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 640, 151, 35))
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 640, 700, 35))
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(870, 10, 141, 61))
        self.groupBox.setTitle("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, -10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(0, 30, 141, 31))
        self.comboBox.setFont(font)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 10, 701, 61))
        self.groupBox_2.setTitle("")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 20, 121, 20))
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 30, 111, 31))
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(590, 0, 111, 31))
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(440, 20, 141, 20))
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(70, 20, 131, 20))
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Обрахувати"))
        self.pushButton_2.setText(_translate("MainWindow", "Зберегти"))
        self.label.setText(_translate("MainWindow", "Виберіть алгоритм"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Алгоритм Прима"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Алгоритм Крускала"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Алгоритм Борувки"))
        self.radioButton_2.setText(_translate("MainWindow", "Додати ребро"))
        self.pushButton_4.setText(_translate("MainWindow", "Задати"))
        self.radioButton_3.setText(_translate("MainWindow", "Задати вагу ребра"))
        self.radioButton.setText(_translate("MainWindow", "Додати вершину"))
        self.pushButton_3.setText(_translate("MainWindow", "Видалити граф"))
